const questions = [
  { topic:'Git foundations', icon:'⌘', title:'What does `git clone` do?', options:['Deletes a repository','Copies a remote repository locally','Creates an empty branch','Formats Python files'], answer:1, note:'Clone downloads the repository, including its history, to your machine.' },
  { topic:'Git branches', icon:'⑂', title:'What is special about an orphan branch?', options:['It cannot contain files','Its first commit has no parent history','It automatically gets pushed','It only works with Python'], answer:1, note:'An orphan branch starts a completely separate commit history.' },
  { topic:'Python environments', icon:'◒', title:'What does `uv add langchain` update?', options:['Your browser','Project dependencies and the lockfile','Your Git author','The macOS PATH'], answer:1, note:'uv records the dependency in pyproject.toml and updates uv.lock.' },
  { topic:'Environment variables', icon:'◆', title:'Why use `load_dotenv()`?', options:['To format imports','To load values from `.env` into the environment','To create a Git branch','To start Ollama'], answer:1, note:'It reads key/value pairs from .env so your code can access them with os.getenv().' },
  { topic:'Python basics', icon:'λ', title:'What does `if __name__ == "__main__":` mean?', options:['Always skip main()','Run the block when the file is executed directly','Install Python','Set the API key'], answer:1, note:'Python sets __name__ to __main__ when that file is the entry point.' },
  { topic:'Code formatting', icon:'✦', title:'What does `black .` do?', options:['Runs every test','Formats Python files in the current directory','Sorts Git commits','Creates a virtual environment'], answer:1, note:'Black applies consistent automatic formatting to Python code.' },
  { topic:'Import hygiene', icon:'↕', title:'What does `isort .` organize?', options:['Python import statements','Environment variables','Git branches','Markdown headings'], answer:0, note:'isort sorts imports into a consistent, readable order.' },
  { topic:'OpenAI integration', icon:'◎', title:'What should you avoid committing to Git?', options:['README.md','Your API key in `.env`','A Python function','A package lockfile'], answer:1, note:'Keep secrets private. The project .gitignore should exclude .env.' },
];
const state = JSON.parse(localStorage.getItem('learningHubState') || '{"answered":{},"score":0}');
let current = 0;
const $ = (id) => document.getElementById(id);
function renderTopics() { $('topic-grid').innerHTML = questions.map((q,i) => `<article class="topic ${state.answered[i] ? 'done' : ''}"><span class="check">✓</span><div class="topic-icon">${q.icon}</div><h3>${q.topic}</h3><p>${q.title.replaceAll('`','')}</p></article>`).join(''); const done = Object.keys(state.answered).length; $('completed-count').textContent = done; $('total-count').textContent = questions.length; const percent = Math.round(done / questions.length * 100); $('progress-percent').textContent = `${percent}%`; $('ring').style.background = `conic-gradient(var(--orange) ${percent * 3.6}deg, #f0eeea 0deg)`; }
function renderQuestion() { const q = questions[current]; $('question-number').textContent = `QUESTION ${current + 1} / ${questions.length}`; $('question-topic').textContent = q.topic; $('question-text').textContent = q.title; $('answers').innerHTML = q.options.map((a,i) => `<button class="answer" data-index="${i}">${a}</button>`).join(''); $('feedback').textContent = ''; $('feedback').className = 'feedback'; $('next-button').disabled = true; $('next-button').textContent = 'Choose an answer'; document.querySelectorAll('.answer').forEach(btn => btn.addEventListener('click', () => choose(Number(btn.dataset.index)))); }
function choose(index) { const q = questions[current]; const buttons = document.querySelectorAll('.answer'); buttons.forEach(b => b.disabled = true); buttons[q.answer].classList.add('correct'); const good = index === q.answer; if (!state.answered[current]) { state.answered[current] = true; if (good) state.score++; localStorage.setItem('learningHubState', JSON.stringify(state)); } if (!good) buttons[index].classList.add('incorrect'); $('feedback').textContent = good ? `Correct — ${q.note}` : `Not quite. ${q.note}`; $('feedback').className = `feedback ${good ? 'good' : 'bad'}`; $('score-label').textContent = `${state.score} correct so far`; $('next-button').disabled = false; $('next-button').textContent = current === questions.length - 1 ? 'Start again' : 'Next question'; renderTopics(); }
$('next-button').addEventListener('click', () => { current = current === questions.length - 1 ? 0 : current + 1; renderQuestion(); }); $('reset-button').addEventListener('click', () => { localStorage.removeItem('learningHubState'); location.reload(); }); $('date').textContent = new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date()); renderTopics(); renderQuestion();
