const lessons = [
  { id:'clone', topic:'Git foundations', icon:'⌘', title:'Clone a project', command:'git clone https://github.com/emarco177/langchain-course.git', explain:'git clone copies a remote repository onto your computer. It creates a new folder, downloads the files, and preserves the project history so Git can track future work.', line:'git clone <repository-url>', check:'Which command copies a remote repository locally?', options:['git copy','git clone','git download','git init'], answer:1, why:'Use git clone when the project already exists on a remote such as GitHub.' },
  { id:'branch', topic:'Git branches', icon:'⑂', title:'Start an isolated lesson branch', command:'git checkout --orphan project/hello-world', explain:'An orphan branch starts a new, unrelated commit history. It is useful when you want a clean project line. A normal branch (`git switch -c name`) keeps the existing history.', line:'git checkout --orphan <branch-name>', check:'What makes an orphan branch different?', options:['It has no parent commit history','It cannot be pushed','It deletes Git','It only works on GitHub'], answer:0, why:'The first commit on an orphan branch has no parent from the branch you came from.' },
  { id:'uv', topic:'Project dependencies', icon:'◒', title:'Add Python packages with uv', command:'uv add langchain\nuv add langchain-openai\nuv add python-dotenv\nuv add langchain-ollama', explain:'uv manages the project environment and dependencies. `uv add` records packages in pyproject.toml and resolves exact versions into uv.lock, making the setup reproducible.', line:'uv add <package-name>', check:'What does uv add update?', options:['Only the browser','pyproject.toml and uv.lock','Your Git username','The macOS desktop'], answer:1, why:'The project manifest describes dependencies; the lockfile records the resolved installation.' },
  { id:'env', topic:'Environment variables', icon:'◆', title:'Load configuration safely', command:'from dotenv import load_dotenv\nimport os\nload_dotenv()\napi_key = os.environ.get("OPENAI_API_KEY")', explain:'`load_dotenv()` reads key/value pairs from a local `.env` file. `os.environ.get(...)` reads a value without crashing when it is missing. Never commit or print a real API key.', line:'print(bool(os.environ.get("OPENAI_API_KEY")))', check:'Why should you test an API key with bool(...) instead of printing it?', options:['It is faster','It avoids exposing the secret','It creates the key','It formats Python'], answer:1, why:'A boolean confirms whether a value exists without revealing the credential.' },
  { id:'main', topic:'Python entry points', icon:'λ', title:'Define and call main()', command:'def main():\n    print("Hello from langchain-course!")\n\nif __name__ == "__main__":\n    main()', explain:'A function groups reusable behavior. Python sets `__name__` to `"__main__"` when the file is run directly, so the guarded block calls main without running on import.', line:'if __name__ == "__main__":', check:'When does the guarded main() call run?', options:['Only when the file is executed directly','Whenever it is imported','Never','When Git commits'], answer:0, why:'The guard distinguishes direct execution from importing the module elsewhere.' },
  { id:'format', topic:'Code formatting', icon:'✦', title:'Format consistently', command:'black .', explain:'Black reformats Python files using consistent rules. It changes layout, spacing, and line wrapping, but should not change the program’s intended behavior.', line:'uv run black .', check:'What is Black for?', options:['Formatting Python code','Installing Git','Running a server','Creating API keys'], answer:0, why:'Formatting removes distracting style decisions so you can focus on behavior.' },
  { id:'imports', topic:'Import hygiene', icon:'↕', title:'Sort imports', command:'isort .', explain:'isort organizes import statements into a predictable order. Running it before or alongside Black keeps files readable and reduces noisy formatting differences.', line:'uv run isort .', check:'What does isort organize?', options:['Git branches','Python imports','Environment variables','Quiz scores'], answer:1, why:'isort is specifically an import sorter.' },
  { id:'commit', topic:'Git save point', icon:'✓', title:'Stage and commit', command:'git status\ngit add .\ngit commit -m "environment setup"', explain:'git status previews the working tree. git add stages selected changes. git commit creates a local save point. Review status before committing and keep `.env` ignored.', line:'git status → git add . → git commit -m "message"', check:'What does git add . do?', options:['Pushes to GitHub','Stages current-directory changes','Deletes the branch','Installs packages'], answer:1, why:'Staging is the review area between editing and creating a commit.' },
  { id:'imports-lesson2', topic:'Lesson 2 · Imports', icon:'↳', title:'Import the tools you need', command:'from dotenv import load_dotenv\nfrom langchain_core.prompts import PromptTemplate\nfrom langchain_openai import ChatOpenAI\nimport os', explain:'Each import brings a capability into this file: dotenv loads local configuration, PromptTemplate builds reusable prompts, ChatOpenAI connects LangChain to an OpenAI chat model, and os reads environment variables.', line:'from package import name', check:'What does an import do?', options:['Makes a module’s names available in this file','Sends a Git commit','Creates an API key','Runs every function'], answer:0, why:'Imports connect your file to code provided by Python or installed packages.' },
  { id:'dotenv-lesson2', topic:'Lesson 2 · Configuration', icon:'◆', title:'Load the .env file', command:'load_dotenv()', explain:'Call load_dotenv() before reading environment variables. It loads local key/value settings into the process so libraries can find configuration without hard-coding secrets.', line:'load_dotenv()', check:'When should load_dotenv() run?', options:['Before reading environment variables','After the model response','Only during git push','Instead of importing os'], answer:0, why:'Loading first ensures later environment lookups can see the values.' },
  { id:'template-lesson2', topic:'Lesson 2 · PromptTemplate', icon:'▤', title:'Create a reusable prompt', command:'summary_prompt_template = PromptTemplate(\n    input_variables=["information"],\n    template=summary_template,\n)', explain:'PromptTemplate combines a template string containing {information} with a declared input variable. Later, the chain fills that placeholder with the actual text.', line:'PromptTemplate(input_variables=["information"], template=summary_template)', check:'What must input_variables contain here?', options:['The placeholder name information','The API key value','The model name','The output text'], answer:0, why:'The list names the variables that the template expects at invocation time.' },
  { id:'model-lesson2', topic:'Lesson 2 · Model', icon:'◎', title:'Configure the chat model', command:'llm = ChatOpenAI(temperature=0, model="gpt-5")', explain:'ChatOpenAI creates a model client. temperature=0 asks for more consistent output; model selects which available model receives the prompt. The API key should come from the environment, never source code.', line:'llm = ChatOpenAI(temperature=0, model="gpt-5")', check:'What does temperature=0 generally encourage?', options:['More consistent output','A hotter computer','A new branch','Longer imports'], answer:0, why:'Lower temperature reduces randomness; it does not guarantee identical wording.' },
  { id:'chain-lesson2', topic:'Lesson 2 · LCEL chain', icon:'→', title:'Compose prompt and model', command:'chain = summary_prompt_template | llm', explain:'The pipe operator composes runnable LangChain components. The prompt formats the input first, then the model receives the formatted messages and produces a response.', line:'chain = prompt | llm', check:'What does the pipe connect?', options:['The prompt runnable to the model runnable','Git to GitHub','The .env file to Black','Two Python files on disk'], answer:0, why:'LangChain Expression Language uses | to build a runnable sequence.' },
  { id:'invoke-lesson2', topic:'Lesson 2 · Invocation', icon:'▶', title:'Run the chain and print output', command:'response = chain.invoke({"information": information})\nprint(response.content)', explain:'invoke supplies a dictionary whose key matches the prompt variable. The returned message object stores generated text in .content, which you print for the user.', line:'response = chain.invoke({"information": information})', check:'Why does the input key need to be information?', options:['It matches the prompt placeholder','It is required by Git','It hides the API key','It selects Black'], answer:0, why:'The prompt cannot format a value unless the invocation supplies the matching variable name.' },
  { id:'guard-lesson2', topic:'Lesson 2 · Entry point', icon:'λ', title:'Run main only when executed', command:'if __name__ == "__main__":\n    main()', explain:'This guard calls main when you run python main.py directly. If another file imports main.py, the function is available but the whole program does not start automatically.', line:'if __name__ == "__main__":', check:'What is the correct spelling of the module guard?', options:['if __name__ == "__main__":','if name == main:','if __main__ == name:','if main == true:'], answer:0, why:'Both names use double underscores, and the string is exactly __main__.' },
];
const quiz = [
  { kind:'multiple', lesson:'clone', prompt:'You want a local copy of the course repository. Which command is right?', options:['git clone <url>','git push <url>','uv add git','python clone.py'], answer:0, feedback:'Clone is the download-and-connect operation.' },
  { kind:'truefalse', lesson:'branch', prompt:'True or false: `git switch -c` creates a branch while preserving existing history.', options:['True','False'], answer:0, feedback:'Correct. `--orphan` is the special no-history form.' },
  { kind:'multiple', lesson:'uv', prompt:'Complete the command: `uv add ______`', options:['langchain-ollama','main.py','project/hello-world','OPENAI_API_KEY'], answer:0, feedback:'Packages belong in uv add; files and secrets do not.' },
  { kind:'multiple', lesson:'env', prompt:'Which line safely checks whether a key is present?', options:['print(OPENAI_API_KEY)','print(bool(os.environ.get("OPENAI_API_KEY")))','git add .env','load_dotenv("print")'], answer:1, feedback:'bool gives a safe presence check without exposing the value.' },
  { kind:'multiple', lesson:'main', prompt:'What is the purpose of `def main():`?', options:['Define a reusable function','Install Python','Create a branch','Sort imports'], answer:0, feedback:'A function packages behavior that can be called.' },
  { kind:'truefalse', lesson:'format', prompt:'True or false: Black is a Python formatter.', options:['True','False'], answer:0, feedback:'Black formats Python source consistently.' },
  { kind:'multiple', lesson:'imports', prompt:'Which command sorts imports through uv?', options:['uv run isort .','uv run git .','isort add .','uv import sort'], answer:0, feedback:'uv run executes the project’s installed tool.' },
  { kind:'multiple', lesson:'commit', prompt:'Put the workflow in the right order.', options:['commit → add → status','status → add → commit','add → push → status','status → commit → add'], answer:1, feedback:'Inspect, stage, then commit.' },
  { kind:'multiple', lesson:'imports-lesson2', prompt:'Which import provides PromptTemplate?', options:['from langchain_core.prompts import PromptTemplate','from dotenv import PromptTemplate','import PromptTemplate from os','from langchain_openai import PromptTemplate'], answer:0, feedback:'PromptTemplate is provided by langchain_core.prompts.' },
  { kind:'truefalse', lesson:'dotenv-lesson2', prompt:'True or false: load_dotenv() should run before environment values are read.', options:['True','False'], answer:0, feedback:'Loading first makes the .env values available to os.environ.' },
  { kind:'multiple', lesson:'template-lesson2', prompt:'What does the {information} placeholder represent?', options:['A value supplied when the chain is invoked','The API key itself','The model temperature','A Git branch'], answer:0, feedback:'The invocation dictionary fills the placeholder.' },
  { kind:'multiple', lesson:'model-lesson2', prompt:'Which line creates the chat model client?', options:['llm = ChatOpenAI(temperature=0, model="gpt-5")','llm = PromptTemplate()','chain = prompt | llm','load_dotenv()'], answer:0, feedback:'ChatOpenAI configures the model runnable.' },
  { kind:'multiple', lesson:'chain-lesson2', prompt:'What does `prompt | llm` express?', options:['A runnable prompt-to-model sequence','A shell pipe that deletes files','A Git merge','A Python import'], answer:0, feedback:'The pipe composes LangChain runnables.' },
  { kind:'multiple', lesson:'invoke-lesson2', prompt:'Where is generated text found on the response message?', options:['response.content','response.api_key','response.git','response.prompt_template'], answer:0, feedback:'Message content is the generated text to print or use.' },
  { kind:'multiple', lesson:'guard-lesson2', prompt:'Which condition runs main() only for direct execution?', options:['if __name__ == "__main__":','if name == "main":','if __main__ == "name":','if main():'], answer:0, feedback:'The double-underscore module guard is the Python convention.' },
];
const initial = { learned:{}, quiz:{answered:{}, score:0, attempts:[]}, challenge:false, challengeAttempts:[] };
let state; try { state = {...initial, ...JSON.parse(localStorage.getItem('learningHubState') || '{}')}; } catch { state = {...initial}; }
state.learned ||= {}; state.quiz ||= {answered:{},score:0}; state.quiz.answered ||= {};
state.quiz.attempts ||= []; state.challengeAttempts ||= [];
let currentLesson = 0, currentQuiz = 0;
const $ = (id) => document.getElementById(id);
const save = () => localStorage.setItem('learningHubState', JSON.stringify(state));
function renderLessons() { $('lesson-list').innerHTML = lessons.map((l,i) => `<article class="lesson-card ${state.learned[l.id] ? 'learned' : ''}"><div class="lesson-icon">${l.icon}</div><div class="lesson-copy"><div class="lesson-kicker">${String(i+1).padStart(2,'0')} · ${l.topic}</div><h3>${l.title}</h3><p>${l.explain}</p><pre><code>${l.command}</code></pre><button class="learn-button" data-lesson="${i}">${state.learned[l.id] ? '✓ Learned' : 'Mark as learned'}</button></div></article>`).join(''); document.querySelectorAll('.learn-button').forEach(b => b.addEventListener('click', () => { const l = lessons[Number(b.dataset.lesson)]; state.learned[l.id] = !state.learned[l.id]; save(); renderAll(); })); }
function renderProgress() { const learned = lessons.filter(l => state.learned[l.id]).length, answered = Object.keys(state.quiz.answered).length, total = lessons.length + quiz.length + 1, done = learned + answered + (state.challenge ? 1 : 0), pct = Math.round(done/total*100); $('completed-count').textContent = done; $('total-count').textContent = total; $('progress-percent').textContent = `${pct}%`; $('ring').style.background = `conic-gradient(var(--orange) ${pct*3.6}deg, #f0eeea 0deg)`; $('lesson-progress').textContent = `${learned} / ${lessons.length} concepts learned`; $('score-label').textContent = `${state.quiz.score} / ${quiz.length} correct`; }
function renderQuiz() { const q=quiz[currentQuiz], l=lessons.find(x=>x.id===q.lesson); $('question-number').textContent=`CHECK ${currentQuiz+1} / ${quiz.length}`; $('question-topic').textContent=l.topic; $('question-text').textContent=q.prompt; $('answers').innerHTML=q.options.map((a,i)=>`<button class="answer" data-index="${i}">${a}</button>`).join(''); $('feedback').textContent=''; $('feedback').className='feedback'; $('next-button').disabled=true; $('next-button').textContent='Choose an answer'; document.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>answerQuiz(Number(b.dataset.index)))); }
function answerQuiz(index) { const q=quiz[currentQuiz], buttons=document.querySelectorAll('.answer'), good=index===q.answer; buttons.forEach(b=>b.disabled=true); buttons[q.answer].classList.add('correct'); state.quiz.attempts.push({question:currentQuiz+1, lesson:q.lesson, prompt:q.prompt, selected:q.options[index], correctAnswer:q.options[q.answer], correct:good, at:new Date().toISOString()}); if(!state.quiz.answered[currentQuiz]) { state.quiz.answered[currentQuiz]=true; if(good) state.quiz.score++; } save(); if(!good) buttons[index].classList.add('incorrect'); $('feedback').textContent=good?`Correct — ${q.feedback}`:`Not quite. ${q.feedback}`; $('feedback').className=`feedback ${good?'good':'bad'}`; $('next-button').disabled=false; $('next-button').textContent=currentQuiz===quiz.length-1?'Restart checks':'Next check'; renderProgress(); }
function renderChallenge() { const starter='def greet(name):\n    return f"Hello, {name}!"'; $('challenge-editor').value=state.challengeCode || starter; $('challenge-status').textContent=state.challenge?'Challenge complete — nice work.':'Write a function named greet(name) that returns a greeting containing the name.'; }
function checkChallenge() { const code=$('challenge-editor').value; state.challengeCode=code; const ok=/def\s+greet\s*\(\s*name\s*\)\s*:/i.test(code)&&/return\s+.*name/i.test(code); state.challenge=ok; state.challengeAttempts.push({code, passed:ok, at:new Date().toISOString()}); save(); $('challenge-status').textContent=ok?'Passed — your answer defines greet(name) and returns a name-based greeting.':'Not yet. Add `def greet(name):` and return a string that uses `name`.'; $('challenge-status').className=ok?'challenge-status good':'challenge-status bad'; renderProgress(); }
function buildReport() { const mastery=lessons.map(l=>{const attempts=state.quiz.attempts.filter(a=>a.lesson===l.id), correct=attempts.filter(a=>a.correct).length, status=state.learned[l.id]&&attempts.some(a=>a.correct)?'mastered':attempts.length?'needs-review':'not-started'; return {id:l.id,topic:l.topic,title:l.title,status,tag:status==='mastered'?'strong':status==='needs-review'?'weak':'unseen',learned:!!state.learned[l.id],attemptCount:attempts.length,correctAttempts:correct,quizAttempts:attempts};}); const weak=mastery.filter(m=>m.status!=='mastered').map(m=>m.topic); return {reportVersion:1,generatedAt:new Date().toISOString(),lesson:'Lessons 1–2 · Set up and first chain',summary:{conceptsLearned:mastery.filter(m=>m.learned).length,totalConcepts:lessons.length,quizScore:state.quiz.score,totalQuizQuestions:quiz.length,overallScorePercent:Math.round(state.quiz.score/quiz.length*100),codingChallengePassed:!!state.challenge,weakTopics:weak},mastery,quizAttempts:state.quiz.attempts,codingChallengeAttempts:state.challengeAttempts,instructions:'Share this report with Codex for instructor-style review. It contains learning activity only; do not add secrets.'}; }
function reportMarkdown() { const r=buildReport(); const lines=[`# Learning Hub review — ${r.lesson}`,`Generated: ${r.generatedAt}`,'',`## Overall score`,`- Quiz: ${r.summary.quizScore}/${r.summary.totalQuizQuestions} (${r.summary.overallScorePercent}%)`,`- Concepts learned: ${r.summary.conceptsLearned}/${r.summary.totalConcepts}`,`- Coding challenge passed: ${r.summary.codingChallengePassed?'yes':'not yet'}`,`- Weak / needs review: ${r.summary.weakTopics.join(', ')||'none recorded'}`,'','## Topic tags',...r.mastery.map(m=>`- [${m.tag}] ${m.topic}: ${m.correctAttempts}/${m.attemptCount} correct attempts; ${m.learned?'lesson marked learned':'lesson not marked learned'}`),'','## Quiz attempts',...r.quizAttempts.map(a=>`- ${a.at}: ${a.correct?'correct':'incorrect'} — ${a.lesson}; selected “${a.selected}”, expected “${a.correctAnswer}”`),'','## Coding attempts',...r.codingChallengeAttempts.map(a=>`- ${a.at}: ${a.passed?'passed':'needs revision'}`),'','Paste this note or the downloaded JSON into a later Codex message for targeted revision.']; return lines.join('\n'); }
function download(name,type,text){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function reportStatus(msg){$('report-status').textContent=msg; setTimeout(()=>{$('report-status').textContent='';},3500);}
function renderAll(){renderLessons();renderProgress();renderQuiz();renderChallenge();}
$('next-button').addEventListener('click',()=>{currentQuiz=currentQuiz===quiz.length-1?0:currentQuiz+1;renderQuiz();}); $('check-challenge').addEventListener('click',checkChallenge); $('download-json').addEventListener('click',()=>{download('learning-hub-report.json','application/json',JSON.stringify(buildReport(),null,2));reportStatus('JSON report downloaded.');}); $('download-markdown').addEventListener('click',()=>{download('learning-hub-review.md','text/markdown',reportMarkdown());reportStatus('Review note downloaded.');}); $('copy-report').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(reportMarkdown());reportStatus('Review note copied.');}catch{reportStatus('Copy was unavailable; use Download review note.');}}); $('reset-button').addEventListener('click',()=>{localStorage.removeItem('learningHubState');location.reload();}); $('date').textContent=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date()); renderAll();
